development:
  adapter: postgresql
  database: csas_development
  encoding: utf8
  username: dev
  password: hipass
  host: 127.0.0.1

test: &TEST
  adapter: postgresql
  database: csas_test
  encoding: utf8
  username: dev
  password: hipass
  host: 127.0.0.1

